version: '3.0'
services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        ports:
          - '80:80'
          - '443:443'
        networks:
          - 'dev'
        volumes:
          - './gitlab/config:/etc/gitlab'
          - './gitlab/logs:/var/log/gitlab'
          - './gitlab/data:/var/opt/gitlab'
    sonarqube:
        image: 'sonarqube:latest'
        #image: 'sonarqube:7.6-community'
        ports:
          - '9000:9000'
        networks:
          - 'dev'
        volumes:
          - './sonarqube/data:/opt/sonarqube/data'
          - './sonarqube/conf:/opt/sonarqube/conf'
          - './sonarqube/extensions:/opt/sonarqube/extensions'
networks:
  dev:
