version: '3.0'
services:
    web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:80'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    networks:
      - 'dev'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    sonarqube:
    image: 'sonarqube:7.6-community'
    ports:
      - '9000:9000'
    networks:
      - 'dev'
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_logs:/opt/sonarqube/logs'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
networks:
  dev:
volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
